[CmdletBinding()]
param(
    [string]$RepoRoot = ".",
    [switch]$Apply,
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$resolvedRoot = (Resolve-Path -Path $RepoRoot).Path
$queryPlan = Join-Path $resolvedRoot "tools/agents/query-plan-ledger.ps1"
$queryMemory = Join-Path $resolvedRoot "tools/agents/query-memory.ps1"
$appendMemory = Join-Path $resolvedRoot "tools/agents/append-memory.ps1"

if (-not (Test-Path $queryPlan) -or -not (Test-Path $queryMemory)) {
    Write-Error "Required scripts not found."
    exit 1
}

$plans = @((powershell -ExecutionPolicy Bypass -File $queryPlan -RepoRoot $resolvedRoot -Limit 500 | ConvertFrom-Json))
$memoryAll = @((powershell -ExecutionPolicy Bypass -File $queryMemory -Limit 5000 | ConvertFrom-Json))
$supersededIds = New-Object System.Collections.Generic.HashSet[string]
foreach ($entry in $memoryAll) {
    foreach ($sup in @($entry.supersedes)) {
        $supId = [string]$sup
        if (-not [string]::IsNullOrWhiteSpace($supId)) {
            [void]$supersededIds.Add($supId)
        }
    }
}
$memoryOpen = @($memoryAll | Where-Object {
    ([string]$_.status -eq "open") -and (-not $supersededIds.Contains([string]$_.id))
})

$planStatus = @{}
foreach ($entry in $plans) {
    if ($null -eq $entry.planId) { continue }
    if (-not $planStatus.ContainsKey($entry.planId) -or $entry.isUpdate) {
        $planStatus[$entry.planId] = [string]$entry.status
    }
}

$issues = New-Object System.Collections.ArrayList
foreach ($m in $memoryOpen) {
    $topic = [string]$m.topic
    if (-not $topic.StartsWith("plan:")) { continue }

    $planId = $topic.Substring(5)
    if ($planId -match "^(PLN-\d{8}-\d{4})(-.+)?$") {
        $planId = $Matches[1]
    }
    if (-not $planStatus.ContainsKey($planId)) {
        [void]$issues.Add([ordered]@{ type = "orphan_memory_topic"; planId = $planId; topic = $topic; memoryId = [string]$m.id; message = "Memory topic has no ledger plan." })
        continue
    }

    $status = [string]$planStatus[$planId]
    if ($status -eq "done" -or $status -eq "canceled") {
        [void]$issues.Add([ordered]@{ type = "open_memory_for_closed_plan"; planId = $planId; topic = $topic; memoryId = [string]$m.id; message = "Plan is closed in ledger but memory topic remains open." })
    }
}

$report = [ordered]@{
    generatedUtc = [DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')
    issueCount = $issues.Count
    issues = @($issues.ToArray())
}

if ($Apply -and $issues.Count -gt 0 -and -not $DryRun) {
    foreach ($issue in $issues) {
        $targetTopic = [string]$issue.topic
        if ([string]::IsNullOrWhiteSpace($targetTopic)) {
            $targetTopic = "plan:$($issue.planId)"
        }
        if ($issue.type -eq "open_memory_for_closed_plan") {
            powershell -ExecutionPolicy Bypass -File $appendMemory `
                -Kind note `
                -Topic $targetTopic `
                -Summary ("Reconcile close: plan " + $issue.planId + " marked done in ledger; closing open memory topic.") `
                -Details "Generated by reconcile-plan-memory.ps1" `
                -Scope tooling `
                -Status done `
                -Tags plans,reconcile,agents `
                -Refs "docs/agents/Plans.md" `
                -Supersedes $issue.memoryId | Out-Null
            continue
        }

        if ($issue.type -eq "orphan_memory_topic") {
            powershell -ExecutionPolicy Bypass -File $appendMemory `
                -Kind note `
                -Topic $targetTopic `
                -Summary ("Reconcile deprecate: orphan memory topic without ledger plan (" + $issue.planId + ").") `
                -Details "Generated by reconcile-plan-memory.ps1" `
                -Scope tooling `
                -Status deprecated `
                -Tags plans,reconcile,agents `
                -Refs "docs/agents/Plans.md" `
                -Supersedes $issue.memoryId | Out-Null
        }
    }
}

if ($DryRun) {
    Write-Host "[DryRun] issues=$($issues.Count) apply=$Apply"
    exit 0
}

$report | ConvertTo-Json -Depth 8
exit 0
